// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbohoyihfkdrhjckuosv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtib2hveWloZmtkcmhqY2t1b3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDEwMDIsImV4cCI6MjA2NjM3NzAwMn0.AbKeDOr4Gf4LD-ds9MrGqj66FG9gdbUu4ztMCoXOlTQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);